services:
  db:
    image: postgres:16-alpine
    container_name: fintrack-db
    environment:
      POSTGRES_DB: fintrack_db
      POSTGRES_USER: fintrack_user
      POSTGRES_PASSWORD: fintrack_pass
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fintrack_user -d fintrack_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ./FinTrack
    container_name: fintrack-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/fintrack_db
      SPRING_DATASOURCE_USERNAME: fintrack_user
      SPRING_DATASOURCE_PASSWORD: fintrack_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      JWT_SECRET: ZmluLXRyYWNrLXNlY3JldC1rZXktMjU2LWJpdHMtcGFyYS1obWFjLXNoYTI1Ni1hbGdvcml0aG1v
      JWT_EXPIRATION: "86400000"
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
    container_name: fintrack-frontend
    depends_on:
      - app
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  pgdata:
