spring.application.name=FinTrack

# PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/fintrack_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:fintrack_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:fintrack_pass}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# Server
server.port=8080

# JWT
jwt.secret=${JWT_SECRET:ZmluLXRyYWNrLXNlY3JldC1rZXktMjU2LWJpdHMtcGFyYS1obWFjLXNoYTI1Ni1hbGdvcml0aG1v}
jwt.expiration=${JWT_EXPIRATION:86400000}
